Fix: execution zctl only from install path
If zctl is installed in a location other than the desktop, it becomes
problematic to run it. `cd`-ing every time - it is not quite usable way.
In fact, you shouldn't bind to the current working folder.

This commit allows you to run the script through PATH just like regular
installed programs. You can symlink to `/usr/share/local` or
`~/.local/bin/` if you like, and everything should work.

diff --git a/zctl b/zctl
--- a/zctl
+++ b/zctl
@@ -1,32 +1,36 @@
 #!/bin/bash
 
+_scriptpath="$(dirname "$(readlink -f "$0")")"
+
+cd "${_scriptpath}" || { printf '%s' 'Cannot cd to script directory' >&2 ; exit 1 ;}
+
 case "$1" in
   "start")
-    python3 cameras.py &
+    python3 "${_scriptpath}/cameras.py" &
   ;;
 
   "stop")
-    echo EXIT > status
+    echo EXIT > "${_scriptpath}/status"
   ;;
 
   "gui")
-    python3 gui.py &
+    python3 "${_scriptpath}/gui.py" &
   ;;
 
   "passthrough")
-    echo PASSTHROUGH > status
+    echo PASSTHROUGH > "${_scriptpath}/status"
   ;;
 
   "video")
-    echo VIDEO > status
+    echo VIDEO > "${_scriptpath}/status"
   ;;
 
   "image")
-    echo IMAGE > status
+    echo IMAGE > "${_scriptpath}/status"
   ;;
 
   "status")
-    echo Status: $(cat status)
+    echo Status: "$(cat "${_scriptpath}/status")"
   ;;
 
   *)
